### ISSUE TITLE
Profile Data Deleted (or something) and Account Survived? 

### ISSUE THREAD

**Issue by zevelijah** [AbstractPlay/node-backend#1]
Error!

Unable to get user data for [I assume its my UId, tell me if it isn't]
----
I can't really tell the source of it. I clicked on my Ubuntu notification, and I was sent to my Phutball game. Even though it was my turn, and I could see what my opponent had played, I could only use the explore feature, and couldn't actually move. I refreshed a couple times and I just get that error. When I go to my account(greenbaron) settings they asked me to create a new profile. Google remembered what I entered into there, and so I emulated that and clicked submit out of desperation. It said that the display name was already taken. So I went to a new google account, and upon changing the password logged in from there. I still got the same display. I decided to throw caution to the wind after that, and just create a new account upon doing so I was able to access the profile settings, where my email address was properly remembered, but nothing else was. I can no longer play my Phutball game, because I have practically created a new account. I'm not sure if my profile data was simply deleted, because of the display name issue. But I kept the greenbaron account and almost none of its data. But they remembered my email and password. So I suspect you store the email password, and account name on a separate branch from the profile stuff. The profile stuff was deleted, so your code's (completely justified) assumption was I had just made an account. Of course, that's all speculation. 

Anyways, I'm probably sending this issue to the wrong repo, I'll resend it as necessary.

**Comment by Perlkonig** [comment]
Hi, Zev. I'm sorry you're having issues. If you're up to using Discord, that's the simplest way to report errors (https://discord.abstractplay.com), but this is fine. An issue on any of the repos will get flagged.

You are correct that your username/password data is held by a different subsystem than where your user profile is saved. Your profile hasn't been deleted, but it isn't showing any active games. Were you just involved in that one Phutball game? Had the game ended? Or were there a bunch of games you were in? Let me know, and that will inform how I proceed.

**Comment by zevelijah** [comment]
I was in the one Phutball game that was still going on, and as mentioned before, and a cannon game that was also still on but it was my opponents turn at the time of the error.

**Comment by Perlkonig** [comment]
I don't know how this happened, but your list of active games got nuked. I will try to figure out why. Your Cannon game with Eycka is over, but your Phutball game is still ongoing. I *think* I've fixed the problem. Are you able to see the game now?

**Comment by zevelijah** [comment]
Yes, that's fascinating. Well I think you fixed it.
